### ISSUE TITLE
Interface error rate macro set to a low value during SNMPv2 discovery.

### ISSUE THREAD

**Issue by peterwargo** [mrRobit/Zabbix_templates#4]
After successfully installing both this template and the one it depends on (Template Module Interfaces SNMPv2), we started receiving "Warning" level messages about high rates of interface errors.  After much digging, we discovered that the macro that triggered it was set to a very low value in the "Template Module Interfaces SNMPv2" template.  (Which, I know, is not part of this template, but the results seem to affect it in a negative way.

Specifically, the macro is {$IF_ERRORS_WARN} and is set in the SNMPv2 template to a value of "2".  The trigger goes off whenever the error rate goes over 80% of that value, which is pretty low.  Additionally, we're unable to find evidence on either the Palo Alto or the connected network switches that there are any errors at all.

The workaround was to add the {$IF_ERRORS_WARN} macro to this Palo Alto template, and set the value to 20.  That cured the issue, but leaves an underlying question about the validity of the measurement.

For the record, the relevant details are:
-Palo Alto Alto Pa-820
- PanOS 10.1
- Zabbix 5.4

**Comment by mrRobit** [comment]
Due to multiple reported issues with Linked template "Template Module Interfaces SNMPv2" I had to remove it from the Palo Alto template, as do not have any direct impact on this officially supported template. I updated the new version.
You can still add the interface template to your FW host separately.
@peterwargo your behaviour with the errors should be treated as a real problem. Generating errors is most probably caused with the infrastructure itself.
